
Welcome to Sopel. Loading modules...


Downloading malwaredomains db...
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)


Registered 40 modules,
1 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading ipython: No module named 'IPython' (modules/ipython.py:23)


Registered 40 modules,
1 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading ipython: No module named 'IPython' (modules/ipython.py:23)


Registered 40 modules,
1 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...


Error loading ipython: No module named 'IPython' (modules/ipython.py:23)


Registered 40 modules,
1 modules failed to load



Welcome to Sopel. Loading modules...


Error loading ipython: No module named 'IPython' (modules/ipython.py:23)


Registered 40 modules,
1 modules failed to load



Welcome to Sopel. Loading modules...


Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
Error loading redmine: No module named 'dateutil' (../../../../../../home/knifebot/.sopel/modules/redmine.py:21)
Error in calibre setup procedure: 'Config' object has no attribute 'calibre' (config/__init__.py:168)
Error in helpbot setup procedure: 'Config' object has no attribute 'helpbot' (config/__init__.py:168)
Error loading bucket: No module named 'MySQLdb' (../../../../../../home/knifebot/.sopel/modules/bucket.py:37)
Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/__init__.py:168)
Error in document setup procedure: 'Config' object has no attribute 'document' (config/__init__.py:168)
Error in imgur setup procedure: 'Config' object has no attribute 'imgur' (config/__init__.py:168)
Error loading twit: No module named 'tweepy' (../../../../../../home/knifebot/.sopel/modules/twit.py:10)
Error loading dicelog: cannot import name 'calculate' (../../../../../../home/knifebot/.sopel/modules/dicelog.py:15)
Error loading bookie: cannot import name 'exclusion_char' (../../../../../../home/knifebot/.sopel/modules/bookie.py:31)


Registered 50 modules,
11 modules failed to load


Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python3.4/dist-packages/sopel/modules/reload.py", line 49, in f_reload
    bot.unregister(obj)
  File "/usr/local/lib/python3.4/dist-packages/sopel/bot.py", line 170, in unregister
    self._callables[obj.priority][rule].remove(obj)
ValueError: list.remove(x): x not in list

Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.4/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3.4/asynchat.py", line 171, in handle_read
    self.found_terminator()
  File "/usr/local/lib/python3.4/dist-packages/sopel/irc.py", line 382, in found_terminator
    self.dispatch(pretrigger)
  File "/usr/local/lib/python3.4/dist-packages/sopel/bot.py", line 280, in dispatch
    match = regexp.match(text)
AttributeError: 'str' object has no attribute 'match'

ERROR:sopel.modules.sopel.irc:Fatal error in core, please review exception log
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading dicelog: cannot import name 'calculate' (../../../../../../home/knifebot/.sopel/modules/dicelog.py:15)
Error in document setup procedure: 'Config' object has no attribute 'document' (config/__init__.py:168)
Error in helpbot setup procedure: 'Config' object has no attribute 'helpbot' (config/__init__.py:168)
Error loading twit: No module named 'tweepy' (../../../../../../home/knifebot/.sopel/modules/twit.py:10)
Error loading redmine: No module named 'dateutil' (../../../../../../home/knifebot/.sopel/modules/redmine.py:21)
Error in calibre setup procedure: 'Config' object has no attribute 'calibre' (config/__init__.py:168)
Error loading bucket: No module named 'MySQLdb' (../../../../../../home/knifebot/.sopel/modules/bucket.py:37)
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/__init__.py:168)
Error in imgur setup procedure: 'Config' object has no attribute 'imgur' (config/__init__.py:168)
Error loading bookie: cannot import name 'exclusion_char' (../../../../../../home/knifebot/.sopel/modules/bookie.py:31)


Registered 50 modules,
11 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading redmine: No module named 'dateutil' (../../../../../../home/knifebot/.sopel/modules/redmine.py:21)
Error in calibre setup procedure: 'Config' object has no attribute 'calibre' (config/__init__.py:168)
Error in document setup procedure: 'Config' object has no attribute 'document' (config/__init__.py:168)
Error loading twit: No module named 'tweepy' (../../../../../../home/knifebot/.sopel/modules/twit.py:10)
Error in imgur setup procedure: 'Config' object has no attribute 'imgur' (config/__init__.py:168)
Error in helpbot setup procedure: 'Config' object has no attribute 'helpbot' (config/__init__.py:168)
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/__init__.py:168)
Error loading bookie: cannot import name 'exclusion_char' (../../../../../../home/knifebot/.sopel/modules/bookie.py:31)
Error loading bucket: No module named 'MySQLdb' (../../../../../../home/knifebot/.sopel/modules/bucket.py:37)


Registered 50 modules,
10 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error in imgur setup procedure: 'Config' object has no attribute 'imgur' (config/__init__.py:168)
Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/__init__.py:168)
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)


Registered 43 modules,
3 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error in imgur setup procedure: 'Config' object has no attribute 'imgur' (config/__init__.py:168)
Error in document setup procedure: 'Config' object has no attribute 'document' (config/__init__.py:168)
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/__init__.py:168)


Registered 50 modules,
4 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0-py3.4.egg/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/.sopel/modules/bomb.py", line 30, in start
    (trigger.nick not in bot.ops[trigger.sender] and
KeyError: Identifier('#steelandpenises')

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0-py3.4.egg/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/.sopel/modules/bomb.py", line 30, in start
    (trigger.nick not in bot.ops[trigger.sender] and
KeyError: Identifier('#steelandpenises')

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0-py3.4.egg/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0-py3.4.egg/sopel/modules/reload.py", line 49, in f_reload
    bot.unregister(obj)
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0-py3.4.egg/sopel/bot.py", line 170, in unregister
    self._callables[obj.priority][rule].remove(obj)
AttributeError: 'function' object has no attribute 'priority'

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0-py3.4.egg/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/.sopel/modules/bomb.py", line 30, in start
    (trigger.nick not in bot.ops[trigger.sender] and
KeyError: Identifier('#steelandpenises')

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0-py3.4.egg/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/.sopel/modules/bomb.py", line 30, in start
    (trigger.nick not in bot.ops[trigger.sender] and
KeyError: Identifier('#steelandpenises')


Welcome to Sopel. Loading modules...


Error in imgur setup procedure: 'Config' object has no attribute 'imgur' (config/__init__.py:168)
Error in document setup procedure: 'Config' object has no attribute 'document' (config/__init__.py:168)
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/__init__.py:168)


Registered 50 modules,
4 modules failed to load


KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error in document setup procedure: 'Config' object has no attribute 'document' (config/__init__.py:168)
Error in imgur setup procedure: 'Config' object has no attribute 'imgur' (config/__init__.py:168)
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/__init__.py:168)


Registered 50 modules,
4 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/__init__.py:168)
Error in imgur setup procedure: 'Config' object has no attribute 'imgur' (config/__init__.py:168)
Error in document setup procedure: 'Config' object has no attribute 'document' (config/__init__.py:168)
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)


Registered 50 modules,
4 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading ipython: No module named 'IPython' (modules/ipython.py:23)


Registered 40 modules,
1 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)


Registered 35 modules,
6 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)


Registered 35 modules,
6 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)


Registered 35 modules,
6 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)


Registered 35 modules,
6 modules failed to load



Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)
Error loading hello: invalid syntax (hello.py, line 5) (loader.py:187)


Registered 35 modules,
7 modules failed to load



Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)


Registered 36 modules,
6 modules failed to load



Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)


Registered 36 modules,
6 modules failed to load



Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)
Error loading hello: 'module' object has no attribute 'nickname_command' (../../.sopel/modules/hello.py:3)


Registered 35 modules,
7 modules failed to load



Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)


Registered 36 modules,
6 modules failed to load



Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)
Error loading hello: 'module' object has no attribute 'nickname_command' (../../.sopel/modules/hello.py:3)


Registered 35 modules,
7 modules failed to load



Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)
Error loading hello: 'module' object has no attribute 'nickname_command' (../../.sopel/modules/hello.py:3)


Registered 35 modules,
7 modules failed to load


Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 115, in f_load
    load_module(bot, name, path, type_)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 67, in load_module
    module, mtime = sopel.loader.load_module(name, path, type_)
  File "/home/knifebot/sopel-master/sopel/loader.py", line 187, in load_module
    module = imp.load_module(name, mod, path, ('.py', 'U', type_))
  File "/home/knifebot/.sopel/modules/hello.py", line 3, in <module>
    @module.nickname_command('bye!?')
AttributeError: 'module' object has no attribute 'nickname_command'


Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)
Error loading hello: 'module' object has no attribute 'nickname_command' (../../.sopel/modules/hello.py:3)


Registered 35 modules,
7 modules failed to load



Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)
Error loading hello: 'module' object has no attribute 'nickname_command' (../../.sopel/modules/hello.py:3)


Registered 35 modules,
7 modules failed to load


Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 115, in f_load
    load_module(bot, name, path, type_)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 67, in load_module
    module, mtime = sopel.loader.load_module(name, path, type_)
  File "/home/knifebot/sopel-master/sopel/loader.py", line 187, in load_module
    module = imp.load_module(name, mod, path, ('.py', 'U', type_))
  File "/home/knifebot/.sopel/modules/hello.py", line 3, in <module>
    @module.nickname_command('echo', 'repeat')
AttributeError: 'module' object has no attribute 'nickname_command'

Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 115, in f_load
    load_module(bot, name, path, type_)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 67, in load_module
    module, mtime = sopel.loader.load_module(name, path, type_)
  File "/home/knifebot/sopel-master/sopel/loader.py", line 187, in load_module
    module = imp.load_module(name, mod, path, ('.py', 'U', type_))
  File "/home/knifebot/.sopel/modules/hello.py", line 3, in <module>
    @sopel.module.nickname_command('echo', 'repeat')
NameError: name 'sopel' is not defined

Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 115, in f_load
    load_module(bot, name, path, type_)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 67, in load_module
    module, mtime = sopel.loader.load_module(name, path, type_)
  File "/home/knifebot/sopel-master/sopel/loader.py", line 187, in load_module
    module = imp.load_module(name, mod, path, ('.py', 'U', type_))
  File "/home/knifebot/.sopel/modules/hello.py", line 3, in <module>
    @rule('$nick' '(!)(test|man)')
NameError: name 'rule' is not defined


Welcome to Sopel. Loading modules...


Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)
Error in hello setup procedure: '_sre.SRE_Pattern' object has no attribute 'replace' (loader.py:111)


Registered 35 modules,
7 modules failed to load


Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 49, in f_reload
    bot.unregister(obj)
  File "/home/knifebot/sopel-master/sopel/bot.py", line 170, in unregister
    self._callables[obj.priority][rule].remove(obj)
ValueError: list.remove(x): x not in list

Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/tld.py", line 28, in gettld
    if tld[0] == '.':
TypeError: 'NoneType' object has no attribute '__getitem__'

Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/movie.py", line 29, in movie
    u = web.get(uri, 30)
  File "/home/knifebot/sopel-master/sopel/web.py", line 74, in get
    u = get_urllib_object(uri, timeout, headers, verify_ssl)
  File "/home/knifebot/sopel-master/sopel/web.py", line 225, in get_urllib_object
    u = opener.open(req, None, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 113] No route to host>

Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/movie.py", line 29, in movie
    u = web.get(uri, 30)
  File "/home/knifebot/sopel-master/sopel/web.py", line 74, in get
    u = get_urllib_object(uri, timeout, headers, verify_ssl)
  File "/home/knifebot/sopel-master/sopel/web.py", line 225, in get_urllib_object
    u = opener.open(req, None, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/movie.py", line 29, in movie
    u = web.get(uri, 30)
  File "/home/knifebot/sopel-master/sopel/web.py", line 74, in get
    u = get_urllib_object(uri, timeout, headers, verify_ssl)
  File "/home/knifebot/sopel-master/sopel/web.py", line 225, in get_urllib_object
    u = opener.open(req, None, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 115, in f_load
    load_module(bot, name, path, type_)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 74, in load_module
    module.setup(bot)
  File "/home/knifebot/.sopel/modules/ai.py", line 15, in setup
    if bot.config.ai and bot.config.ai.frequency:
  File "/home/knifebot/sopel-master/sopel/config/__init__.py", line 168, in __getattr__
    % (type(self).__name__, name))
AttributeError: 'Config' object has no attribute 'ai'

Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 63, in f_reload
    load_module(bot, name, path, type_)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 74, in load_module
    module.setup(bot)
  File "/home/knifebot/.sopel/modules/ai.py", line 15, in setup
    if bot.config.ai and bot.config.ai.frequency:
  File "/home/knifebot/sopel-master/sopel/config/__init__.py", line 168, in __getattr__
    % (type(self).__name__, name))
AttributeError: 'Config' object has no attribute 'ai'

Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 63, in f_reload
    load_module(bot, name, path, type_)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 74, in load_module
    module.setup(bot)
  File "/home/knifebot/.sopel/modules/ai.py", line 15, in setup
    if bot.config.ai and bot.config.ai.frequency:
  File "/home/knifebot/sopel-master/sopel/config/__init__.py", line 168, in __getattr__
    % (type(self).__name__, name))
AttributeError: 'Config' object has no attribute 'ai'


Welcome to Sopel. Loading modules...


Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/__init__.py:168)
Error loading currency: No module named xmltodict (modules/currency.py:11)
Error loading weather: No module named feedparser (modules/weather.py:15)
Error loading ip: No module named pygeoip (modules/ip.py:9)
Error loading reddit: No module named praw (modules/reddit.py:17)
Error loading ipython: No module named IPython (modules/ipython.py:23)
Error loading bugzilla: No module named xmltodict (modules/bugzilla.py:9)
Error in hello setup procedure: '_sre.SRE_Pattern' object has no attribute 'replace' (loader.py:111)


Registered 35 modules,
8 modules failed to load


Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 49, in f_reload
    bot.unregister(obj)
  File "/home/knifebot/sopel-master/sopel/bot.py", line 170, in unregister
    self._callables[obj.priority][rule].remove(obj)
AttributeError: 'function' object has no attribute 'priority'

KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 43 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...




Registered 43 modules,
0 modules failed to load


KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 43 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...




Registered 43 modules,
0 modules failed to load


KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 43 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...


Error in hello setup procedure: '_sre.SRE_Pattern' object has no attribute 'replace' (loader.py:111)


Registered 42 modules,
1 modules failed to load


KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 42 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 42 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 42 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 42 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...


Error loading youtube: No module named apiclient.discovery (../../.sopel/modules/youtube.py:9)


Registered 42 modules,
1 modules failed to load


Traceback (most recent call last):
  File "/home/knifebot/sopel-master/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 115, in f_load
    load_module(bot, name, path, type_)
  File "/home/knifebot/sopel-master/sopel/modules/reload.py", line 67, in load_module
    module, mtime = sopel.loader.load_module(name, path, type_)
  File "/home/knifebot/sopel-master/sopel/loader.py", line 187, in load_module
    module = imp.load_module(name, mod, path, ('.py', 'U', type_))
  File "/home/knifebot/.sopel/modules/youtube.py", line 9, in <module>
    import apiclient.discovery
ImportError: No module named apiclient.discovery

KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading youtube: name 'AIzaSyATqhwFy6M2l4EuB6AZ97xLCVE5vv' is not defined (../../../../../../home/knifebot/.sopel/modules/youtube.py:12)


Registered 43 modules,
1 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error in youtube setup procedure: Missing required value for youtube.api_key (config/types.py:69)


Registered 43 modules,
1 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python2.7/dist-packages/sopel/modules/reload.py", line 49, in f_reload
    bot.unregister(obj)
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 176, in unregister
    self.shutdown_methods.remove(obj)
ValueError: list.remove(x): x not in list


Welcome to Sopel. Loading modules...


Error in idlerpg setup procedure: '_sre.SRE_Pattern' object has no attribute 'replace' (loader.py:111)


Registered 43 modules,
1 modules failed to load


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python2.7/dist-packages/sopel/modules/reload.py", line 49, in f_reload
    bot.unregister(obj)
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 176, in unregister
    self.shutdown_methods.remove(obj)
ValueError: list.remove(x): x not in list

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python2.7/dist-packages/sopel/modules/reload.py", line 49, in f_reload
    bot.unregister(obj)
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 170, in unregister
    self._callables[obj.priority][rule].remove(obj)
ValueError: list.remove(x): x not in list

KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python2.7/dist-packages/sopel/modules/movie.py", line 29, in movie
    u = web.get(uri, 30)
  File "/usr/local/lib/python2.7/dist-packages/sopel/web.py", line 74, in get
    u = get_urllib_object(uri, timeout, headers, verify_ssl)
  File "/usr/local/lib/python2.7/dist-packages/sopel/web.py", line 225, in get_urllib_object
    u = opener.open(req, None, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 113] No route to host>

KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 45 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Welcome to Sopel. Loading modules...


Error in idlerpg setup procedure: '_sre.SRE_Pattern' object has no attribute 'replace' (loader.py:111)


Registered 44 modules,
1 modules failed to load



Welcome to Sopel. Loading modules...


Error in idlerpg setup procedure: '_sre.SRE_Pattern' object has no attribute 'replace' (loader.py:111)


Registered 44 modules,
1 modules failed to load


KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 45 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 45 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...


Error in idlerpg setup procedure: '_sre.SRE_Pattern' object has no attribute 'replace' (loader.py:111)


Registered 44 modules,
1 modules failed to load



Welcome to Sopel. Loading modules...


Error in idlerpg setup procedure: '_sre.SRE_Pattern' object has no attribute 'replace' (loader.py:111)


Registered 44 modules,
1 modules failed to load



Welcome to Sopel. Loading modules...


Traceback (most recent call last):
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/modules/reload.py", line 92, in f_update
    f_reload(bot, trigger)
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/modules/reload.py", line 39, in f_reload
    bot.setup()
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/bot.py", line 127, in setup
    modules = sopel.loader.enumerate_modules(self.config)
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/loader.py", line 72, in enumerate_modules
    _update_modules_from_dir(modules, directory)
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/loader.py", line 32, in _update_modules_from_dir
    for path in os.listdir(directory):
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/sopel_modules'

KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 45 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...




Registered 45 modules,
0 modules failed to load



Welcome to Sopel. Loading modules...




Registered 45 modules,
0 modules failed to load



Welcome to Sopel. Loading modules...




Registered 45 modules,
0 modules failed to load



Welcome to Sopel. Loading modules...




Registered 45 modules,
0 modules failed to load


/home/knifebot/.local/lib/python2.7/site-packages/sopel/loader.py:67: ImportWarning: Not importing directory '/home/knifebot/.local/lib/python2.7/site-packages/sopel_modules': missing __init__.py
  import sopel_modules

Welcome to Sopel. Loading modules...




Registered 45 modules,
0 modules failed to load



Welcome to Sopel. Loading modules...


Error loading rss: No module named request (modules/rss.py:4)


Registered 45 modules,
1 modules failed to load



Welcome to Sopel. Loading modules...


Error loading rss: No module named request (modules/rss.py:4)


Registered 45 modules,
1 modules failed to load


Traceback (most recent call last):
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/modules/reload.py", line 115, in f_load
    load_module(bot, name, path, type_)
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/modules/reload.py", line 67, in load_module
    module, mtime = sopel.loader.load_module(name, path, type_)
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/loader.py", line 187, in load_module
    module = imp.load_module(name, mod, path, ('.py', 'U', type_))
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel/modules/rss.py", line 4, in <module>
    from urllib.request import urlopen
ImportError: No module named request

KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading github: cannot import name formatting (../sopel_modules/github/github.py:21)
Error loading rss: No module named request (modules/rss.py:4)


Registered 45 modules,
2 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading github: cannot import name formatting (../sopel_modules/github/github.py:21)
Error loading rss: No module named request (modules/rss.py:4)


Registered 45 modules,
2 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading github: cannot import name formatting (../sopel_modules/github/github.py:21)
Error loading rss: No module named request (modules/rss.py:4)


Registered 45 modules,
2 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading rss: No module named request (modules/rss.py:4)


Registered 45 modules,
1 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading youtube: No module named 'apiclient' (../../.sopel/modules/youtube.py:9)
Error loading reddit: No module named 'praw' (modules/reddit.py:17)
Error loading ip: No module named 'pygeoip' (modules/ip.py:9)
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
Error loading currency: No module named 'xmltodict' (modules/currency.py:11)
Error loading bugzilla: No module named 'xmltodict' (modules/bugzilla.py:9)
Error loading weather: No module named 'xmltodict' (modules/weather.py:16)


Registered 37 modules,
7 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
ERROR:sopel.modules.sopel.irc:ERROR recieved from server: Closing link: (unknown@159.203.133.70) [Z-Lined: Your IP range has been attempting to connect too many times in too short a duration. Wait a while, and you will be able to connect.]
Calling shutdown for 0 modules.
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
ERROR:sopel.modules.sopel.irc:ERROR recieved from server: Closing link: (unknown@159.203.133.70) [Z-Lined: Your IP range has been attempting to connect too many times in too short a duration. Wait a while, and you will be able to connect.]
Calling shutdown for 0 modules.
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...


Interrupted

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
ERROR:sopel.modules.sopel.irc:ERROR recieved from server: Closing link: (unknown@159.203.133.70) [Z-Lined: Your IP range has been attempting to connect too many times in too short a duration. Wait a while, and you will be able to connect.]
Calling shutdown for 0 modules.
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...


Interrupted

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
ERROR:sopel.modules.sopel.irc:ERROR recieved from server: Closing link: (unknown@159.203.133.70) [Z-Lined: Your IP range has been attempting to connect too many times in too short a duration. Wait a while, and you will be able to connect.]
Calling shutdown for 0 modules.
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...


Interrupted

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load



Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...




Registered 44 modules,
0 modules failed to load



Welcome to Sopel. Loading modules...


Error in newAI setup procedure: [Errno 2] No such file or directory: u'/home/knifebot/.sopel/markov.txt' (../../../../../../.sopel/modules/newAI.py:33)


Registered 44 modules,
1 modules failed to load


Traceback (most recent call last):
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel-6.0.0-py2.7.egg/sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel-6.0.0-py2.7.egg/sopel/modules/reload.py", line 49, in f_reload
    bot.unregister(obj)
  File "/home/knifebot/.local/lib/python2.7/site-packages/sopel-6.0.0-py2.7.egg/sopel/bot.py", line 170, in unregister
    self._callables[obj.priority][rule].remove(obj)
AttributeError: 'function' object has no attribute 'priority'


Welcome to Sopel. Loading modules...


Error loading junglas: invalid syntax (junglas.py, line 7) (loader.py:187)


Registered 44 modules,
1 modules failed to load


Connecting to 74.207.244.119:6667...
Connected.

Welcome to Sopel. Loading modules...


Error loading junglas: invalid syntax (junglas.py, line 7) (loader.py:187)


Registered 44 modules,
1 modules failed to load



Welcome to Sopel. Loading modules...




Registered 45 modules,
0 modules failed to load


